### ISSUE TITLE
Combination of cats-tagless and scoverage

### ISSUE THREAD

**Issue by Fristi** [typelevel/cats-tagless#19]
When you use cats-tagless autoFunctorK on a algebra with scoverage the coverageReport / coverageAggregate bails out:

```
[error] java.lang.RuntimeException: No source root found for '/Users/markdejong/Projects/test/<macro>' (source roots: '/Users/markdejong/Projects/test/modules/domain/src/main/scala/')
[error]     at scoverage.report.BaseReportWriter.relativeSource(BaseReportWriter.scala:28)
[error]     at scoverage.report.BaseReportWriter.relativeSource(BaseReportWriter.scala:16)
[error]     at scoverage.report.CoberturaXmlWriter.klass(CoberturaXmlWriter.scala:42)
[error]     at scoverage.report.CoberturaXmlWriter.$anonfun$pack$1(CoberturaXmlWriter.scala:66)
[error]     at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error]     at scala.collection.immutable.List.foreach(List.scala:389)
[error]     at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error]     at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error]     at scala.collection.immutable.List.map(List.scala:295)
[error]     at scoverage.report.CoberturaXmlWriter.pack(CoberturaXmlWriter.scala:66)
[error]     at scoverage.report.CoberturaXmlWriter.$anonfun$xml$3(CoberturaXmlWriter.scala:90)
[error]     at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error]     at scala.collection.immutable.List.foreach(List.scala:389)
[error]     at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error]     at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error]     at scala.collection.immutable.List.map(List.scala:295)
[error]     at scoverage.report.CoberturaXmlWriter.xml(CoberturaXmlWriter.scala:90)
[error]     at scoverage.report.CoberturaXmlWriter.write(CoberturaXmlWriter.scala:20)
[error]     at scoverage.ScoverageSbtPlugin$.writeReports(ScoverageSbtPlugin.scala:177)
[error]     at scoverage.ScoverageSbtPlugin$.$anonfun$coverageReport0$1(ScoverageSbtPlugin.scala:124)
[error]     at scoverage.ScoverageSbtPlugin$.$anonfun$coverageReport0$1$adapted(ScoverageSbtPlugin.scala:105)
[error]     at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]     at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]     at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]     at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]     at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]     at sbt.Execute.work(Execute.scala:278)
[error]     at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]     at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]     at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]     at java.lang.Thread.run(Thread.java:748)
```

Related https://github.com/scoverage/scalac-scoverage-plugin/issues/210

**Comment by kailuowang** [comment]
the core functionality of cats-tagless is no longer dependent on scala-meta-macros. 
Migrating to cats-tagless 0.5 without dependencies on `cats-tagless-legacy-macros` will likely fix this.
For an example of such migrations please see
https://github.com/iheartradio/thomas/pull/37/files

**Comment by Fristi** [comment]
I can confirm, it works like a charm now :-)

Thanks for fixing it, feel free to close the issue

**Comment by joroKr21** [comment]
Cats-tagless has migrated to scala.reflect macro annotations in 0.7. Please reopen if the issue persists.
